// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdfjs3v7BfqU_zhZ_ICXN3SO6qIhaRrc',
    appId: '1:350842938153:web:565ddfaa08680076038d38',
    messagingSenderId: '350842938153',
    projectId: 'ecommers-95403',
    authDomain: 'ecommers-95403.firebaseapp.com',
    storageBucket: 'ecommers-95403.appspot.com',
    measurementId: 'G-8V5NDG3T37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedN6rC0HCYOsHF9GQeU5Mno1ZVrxSdrA',
    appId: '1:350842938153:android:9e189dbce854a52f038d38',
    messagingSenderId: '350842938153',
    projectId: 'ecommers-95403',
    storageBucket: 'ecommers-95403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhAtMqxTyTRRU4L0DbYDuQ4YWDTCNSt2k',
    appId: '1:350842938153:ios:1fe6d823dc5f71b3038d38',
    messagingSenderId: '350842938153',
    projectId: 'ecommers-95403',
    storageBucket: 'ecommers-95403.appspot.com',
    iosBundleId: 'com.example.ecommers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhAtMqxTyTRRU4L0DbYDuQ4YWDTCNSt2k',
    appId: '1:350842938153:ios:33b31ecc61f3c61b038d38',
    messagingSenderId: '350842938153',
    projectId: 'ecommers-95403',
    storageBucket: 'ecommers-95403.appspot.com',
    iosBundleId: 'com.example.ecommers.RunnerTests',
  );
}